on: push
jobs:
  build-frontend:
    runs-on: ubuntu-latest
    outputs:
      artifact-name: ${{ steps.upload.outputs.artifact-name }}
    container: node:18
    defaults:
      run:
        working-directory: frontend/intranet
    steps:
      - uses: actions/checkout@v4
      - run: node --version
      - run: npm --version
      - run: npm install
      - run: npm run build-prod
      - name: Upload Frontend Artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: frontend/intranet/dist

  build-backend:
    runs-on: ubuntu-latest
    outputs:
      artifact-name: ${{ steps.upload.outputs.artifact-name }}
    container: node:18
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - run: node --version
      - run: npm --version
      - run: npm install
      - run: npm run build
      - name: Upload Backend Artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: backend-dist
          path: backend/js

  package:
    runs-on: ubuntu-latest
    needs: [build-frontend, build-backend]
    steps:
      - uses: actions/checkout@v4

      - name: Download Frontend Artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-dist
          path: artifacts/frontend

      - name: Download Backend Artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-dist
          path: artifacts

      - name: Package Application
        run: |
          mkdir package
          cp -r artifacts/* package/
          echo "Packaged application with frontend and backend."

      - name: Upload Final Package
        uses: actions/upload-artifact@v4
        with:
          name: full-package
          path: package